// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file TinyYOLOV3.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name

